### ISSUE TITLE
Fix time zones for all cities

### ISSUE THREAD

**Issue by domlander** [domlander/itsfiveoclocksomewhere#3]
The cities time zones are all correct as of right now. As each City changes time zone, the City and time will not pair up.

We should look for a way to check each cities current time to make sure that the time we display next to the City is correct.

**Comment by rahulp959** [comment]
https://developers.google.com/maps/documentation/timezone/overview#Introduction

If you were bored enough to add LatLng to the entries in your current list, you could iterate through them either smartly (narrow down to closest 3 and then only query against that?) Or just all of them?

**Comment by rahulp959** [comment]
Alternately -> https://momentjs.com/timezone/

**Comment by rahulp959** [comment]
If you moved each city to one available in the TimeZone list -> `Europe/London`, `America/Chicago`, you could easily(tm) programmatically enquire about the time for each location using Moment's TZ extension.

**Comment by domlander** [comment]
Using the TimeZoneDB API to get the up-to-date timezone data: https://timezonedb.com/api
